INSERT INTO bears (name,age,gender,color,temperament,alive) VALUES ("Mr. Chocolate",5,"Male","Grey","",1)
("Rowdy",4,"Femal","Grey","",1)
("Tabitha",8,"Femal","Grey","",0)
("Sergeant Brown",9,"Grey","",1)
("Melissa",6,"Femal","Brown","",0)
("Grinch",4,"Femal","Brown","Angry",1)
("Wendy",6,"Male","Brown","Angry",1)
(NULL,8,"Male","Brown","Angry",0)